# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/relationship.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/relationship.proto',
  package='dbimport',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x18proto/relationship.proto\x12\x08\x64\x62import\"\xc1\x03\n\x0cRelationship\x12*\n\x06\x63ourse\x18\x01 \x01(\x0b\x32\x1a.dbimport.Relationship.Key\x12<\n\rprerequisites\x18\x02 \x03(\x0b\x32%.dbimport.Relationship.CourseRelation\x12>\n\x0f\x65quivalent_from\x18\x03 \x03(\x0b\x32%.dbimport.Relationship.CourseRelation\x1a\xc8\x01\n\x03Key\x12\x13\n\x0bschool_name\x18\x01 \x01(\t\x12\x17\n\x0f\x64\x65partment_name\x18\x02 \x01(\t\x12\x15\n\rcourse_number\x18\x03 \x01(\t\x12:\n\x0bschool_type\x18\x04 \x01(\x0e\x32%.dbimport.Relationship.Key.SchoolType\"@\n\nSchoolType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x15\n\x11\x43OMMUNITY_COLLEGE\x10\x01\x12\x0e\n\nUNIVERSITY\x10\x02\x1a<\n\x0e\x43ourseRelation\x12*\n\x06\x63ourse\x18\x01 \x03(\x0b\x32\x1a.dbimport.Relationship.Key')
)



_RELATIONSHIP_KEY_SCHOOLTYPE = _descriptor.EnumDescriptor(
  name='SchoolType',
  full_name='dbimport.Relationship.Key.SchoolType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMMUNITY_COLLEGE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNIVERSITY', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=362,
  serialized_end=426,
)
_sym_db.RegisterEnumDescriptor(_RELATIONSHIP_KEY_SCHOOLTYPE)


_RELATIONSHIP_KEY = _descriptor.Descriptor(
  name='Key',
  full_name='dbimport.Relationship.Key',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='school_name', full_name='dbimport.Relationship.Key.school_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='department_name', full_name='dbimport.Relationship.Key.department_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='course_number', full_name='dbimport.Relationship.Key.course_number', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='school_type', full_name='dbimport.Relationship.Key.school_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RELATIONSHIP_KEY_SCHOOLTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=426,
)

_RELATIONSHIP_COURSERELATION = _descriptor.Descriptor(
  name='CourseRelation',
  full_name='dbimport.Relationship.CourseRelation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='course', full_name='dbimport.Relationship.CourseRelation.course', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=488,
)

_RELATIONSHIP = _descriptor.Descriptor(
  name='Relationship',
  full_name='dbimport.Relationship',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='course', full_name='dbimport.Relationship.course', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prerequisites', full_name='dbimport.Relationship.prerequisites', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='equivalent_from', full_name='dbimport.Relationship.equivalent_from', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RELATIONSHIP_KEY, _RELATIONSHIP_COURSERELATION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=488,
)

_RELATIONSHIP_KEY.fields_by_name['school_type'].enum_type = _RELATIONSHIP_KEY_SCHOOLTYPE
_RELATIONSHIP_KEY.containing_type = _RELATIONSHIP
_RELATIONSHIP_KEY_SCHOOLTYPE.containing_type = _RELATIONSHIP_KEY
_RELATIONSHIP_COURSERELATION.fields_by_name['course'].message_type = _RELATIONSHIP_KEY
_RELATIONSHIP_COURSERELATION.containing_type = _RELATIONSHIP
_RELATIONSHIP.fields_by_name['course'].message_type = _RELATIONSHIP_KEY
_RELATIONSHIP.fields_by_name['prerequisites'].message_type = _RELATIONSHIP_COURSERELATION
_RELATIONSHIP.fields_by_name['equivalent_from'].message_type = _RELATIONSHIP_COURSERELATION
DESCRIPTOR.message_types_by_name['Relationship'] = _RELATIONSHIP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Relationship = _reflection.GeneratedProtocolMessageType('Relationship', (_message.Message,), dict(

  Key = _reflection.GeneratedProtocolMessageType('Key', (_message.Message,), dict(
    DESCRIPTOR = _RELATIONSHIP_KEY,
    __module__ = 'proto.relationship_pb2'
    # @@protoc_insertion_point(class_scope:dbimport.Relationship.Key)
    ))
  ,

  CourseRelation = _reflection.GeneratedProtocolMessageType('CourseRelation', (_message.Message,), dict(
    DESCRIPTOR = _RELATIONSHIP_COURSERELATION,
    __module__ = 'proto.relationship_pb2'
    # @@protoc_insertion_point(class_scope:dbimport.Relationship.CourseRelation)
    ))
  ,
  DESCRIPTOR = _RELATIONSHIP,
  __module__ = 'proto.relationship_pb2'
  # @@protoc_insertion_point(class_scope:dbimport.Relationship)
  ))
_sym_db.RegisterMessage(Relationship)
_sym_db.RegisterMessage(Relationship.Key)
_sym_db.RegisterMessage(Relationship.CourseRelation)


# @@protoc_insertion_point(module_scope)
